# Generated by Django 4.2.2 on 2023-06-26 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("userId", models.IntegerField()),
                ("title", models.CharField()),
                ("body", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("body", models.TextField()),
                (
                    "postId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="liberty_test_task.post",
                    ),
                ),
            ],
        ),
    ]
